### ISSUE TITLE
Replace #include <SDL_opengles2.h> by #include "SDL_opengles2.h"

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-video-rice#47]
@Nebuleon is pointing interesting compilation errors trying to compile on GCW Zero:

`#include <SDL_opengles2.h>` should be replaced by `#include "SDL_opengles2.h"`

**Comment by Nebuleon** [comment]
and other `<>` includes towards SDL, which are added to the **`""`** include path by `sdl2-config --cflags` giving you an `-I` flag:

https://forums.libsdl.org/viewtopic.php?t=5997
http://www.linuxquestions.org/questions/programming-9/gcc-cant-find-sdl-h-but-its-there-133384/#post693844

**Comment by conchurnavid** [comment]
https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html

> #include <file>
> This variant is used for system header files. It searches for a file named file in a standard list of system directories. You can prepend directories to this list with the -I option (see Invocation). 


    sdl2-config --cflags
    -I/usr/include/SDL2 -D_REENTRANT

In contrast the -i option is for the " includes

**Comment by Narann** [comment]
Mmmh after more investigation. I think `#include <SDL_opengles2.h>` is what we want: _system header files_. And as `sdl2-config --cflags` integrate the SDL2 folder we don't want the path.
