### ISSUE TITLE
naming / version conflict

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [mupen64plus/mupen64plus-video-rice#61]
please rename this to mupen64plus-video-rice2 ... or duplicate it and make a mupen64plus-video-rice-legacy ... so that the old version that support old computers can still work in parallel...  without using same settings session, that will have conflicting configs....

**Comment by Narann** [comment]
We could keep a `legacy` branch.

**Comment by MyTDT-Mysoft** [comment]
yes, that's fine, the problem is that as this is a change that worth a new major version... because for example... the new version doesnt work on my laptop (where RICE was the only thing making it work there.... because no glsl 1.2 there (it's OpenGL 2.0.5 there, so i dunno how exactly to fix that yet)... but the anyway the thing is... you should use different config files either for the legacy or for the new branch... to allow both to co-exist, without conflict configurations... for example... here i hexedited rice the legacy one to use [LegacyRice] instead of [Video-Rice], but i think this should be made a official change on the legacy or current branch :)

**Comment by Narann** [comment]
I close this one because there is #62 which is related.
