### ISSUE TITLE
build: Unable to build on aarch64

### ISSUE THREAD

**Issue by pgwipeout** [mupen64plus/mupen64plus-video-rice#85]
aarch64 is not supported.
Building on aarch64 produces the following error:
Makefile:125: *** CPU type "aarch64" not supported.  Please file bug report at 'https://github.com/mupen64plus/mupen64plus-core/issues'.  Stop.

**Comment by enigma9o7** [comment]
Same.  I tried from 2.5.9 source pack.  I had to remove rice from the install script so it would move on to glide and complete...

**Comment by haydenmc** [comment]
I was able to just copy paste the makefile section enabling aarch64 support across from another project. After that, it built just fine and seems to run okay.

After [projects/unix/Makefile@123](https://github.com/mupen64plus/mupen64plus-video-rice/blob/master/projects/unix/Makefile#L123):

```
ifneq ("$(filter aarch64,$(HOST_CPU))","")
    CPU := AARCH
    ARCH_DETECTED := 64BITS
    PIC ?= 1
    NEW_DYNAREC := 1
    NO_ASM := 1
    NO_SSE := 1
endif
```

**Comment by Narann** [comment]
Thanks.

`NEW_DYNAREC` and `NO_SSE` are not supposed to do anything.

```
ifneq ("$(filter aarch64,$(HOST_CPU))","")
    CPU := AARCH
    ARCH_DETECTED := 64BITS
    PIC ?= 1
    NO_ASM := 1
endif
```

If anyone confirm this works, I will add this to the repo.

**Comment by pgwipeout** [comment]
Good Afternoon,

I can confirm that fixes the issue @Narann.
Built without issue native on the Jetson Nano aarch64 board.

**Comment by Narann** [comment]
Modifications have been merged to master. Closing this ticket. Feel free to reopen or open a new one if you have problems.
