### ISSUE TITLE
Mystical Ninja PAL & NTSC-JP versions need options in RiceVideoLinux.ini

### ISSUE THREAD

**Issue by retropieuser** [mupen64plus/mupen64plus-video-rice#94]
I've found that adding these 2 entries in the file will fix the slowdowns in the PAL & JPN versions of Mystical Ninja Starring Goemon. Without them only the US rom works. Can we add this into the file please?

{be0f36f51d69f12b-50}
Name=Mystical Ninja
FastLoadTile
FrameBufferEmulation=0

{8b162c83aecda256-4a}
Name=Ganbare Goemon
FastLoadTile
FrameBufferEmulation=0

**Comment by Narann** [comment]
Thanks !

Fixed by PR #95
